/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-background": "#e5e2e1",
        "surface-container-high": "#2a2a2a",
        "on-primary-fixed": "#161e00",
        "inverse-on-surface": "#313030",
        "surface-container-highest": "#353534",
        "error": "#ffb4ab",
        "tertiary-container": "#d2e5f5",
        "primary-container": "#c3f400",
        "on-error": "#690005",
        "secondary-container": "#fe00fe",
        "on-primary-fixed-variant": "#3c4d00",
        "on-primary": "#283500",
        "surface-container": "#201f1f",
        "on-surface": "#e5e2e1",
        "on-error-container": "#ffdad6",
        "surface": "#131313",
        "outline-variant": "#444933",
        "surface-tint": "#abd600",
        "on-tertiary-fixed-variant": "#374956",
        "on-secondary-fixed": "#380038",
        "on-secondary-container": "#500050",
        "error-container": "#93000a",
        "tertiary-fixed": "#d2e5f5",
        "secondary": "#ffabf3",
        "inverse-surface": "#e5e2e1",
        "surface-container-low": "#1c1b1b",
        "on-tertiary-container": "#556774",
        "on-surface-variant": "#c4c9ac",
        "surface-variant": "#353534",
        "surface-bright": "#3a3939",
        "on-primary-container": "#556d00",
        "on-tertiary": "#21323e",
        "on-secondary-fixed-variant": "#810081",
        "inverse-primary": "#506600",
        "surface-dim": "#131313",
        "primary-fixed": "#c3f400",
        "secondary-fixed": "#ffd7f5",
        "primary-fixed-dim": "#abd600",
        "tertiary": "#ffffff",
        "secondary-fixed-dim": "#ffabf3",
        "background": "#131313",
        "primary": "#ffffff",
        "tertiary-fixed-dim": "#b6c9d8",
        "on-tertiary-fixed": "#0b1d29",
        "outline": "#8e9379",
        "on-secondary": "#5b005b",
        "surface-container-lowest": "#0e0e0e"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "margin-mobile": "16px",
        "unit": "4px",
        "gutter": "24px",
        "margin-desktop": "64px",
        "section-gap": "128px"
      },
      "fontFamily": {
        "headline": ["Bebas Neue", "sans-serif"],
        "body": ["Outfit", "sans-serif"],
      },
    },
  },
  plugins: [],
}
